@url = http://localhost:4500



GET http://localhost:4500/product

###

GET http://localhost:4500/product/1


###
POST {{url}}/signupapi
Content-Type: application/json

{
  "user_name":"Smith",
  "password":234
}

###
POST {{url}}/login
Content-Type:  application/json

{
  "user_name":"Smith",
  "password":234
}

###
POST  {{url}}/addnewproduct
Content-Type:  application/json

{
  "product_name":"test",
  "product_desc":"test",
  "product_price": 123,
  "product_image1": "test",
  "product_image2": "test",
  "product_availability": 12
}


###
PUT {{url}}/update
Content-Type:  application/json

{
  "ProductID":12,
  "product_name":"test",
  "product_desc":"test",
  "product_price":123,
  "product_image1":"test",
  "product_image2":"test",
  "product_availability":1,
  "display":0
}

###
PUT {{url}}/toggledisplay
Content-Type:  application/json

{
  "ProductID":2
}

###
GET {{url}}/product/2

###
DELETE  {{url}}/deleteproduct/12


